server:
  http:
    addr: 0.0.0.0:8010
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9010
    timeout: 1s
data:
  database:
    driver: pgx
    source: postgresql://postgres:postgres.666@127.0.0.1:25432/user?sslmode=disable
  redis:
    addr: 127.0.0.1:26379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  api_key: auth-service-secret
  whitelist: []
