// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-server/internal/data/ent/apiresources"
	"base-server/internal/data/ent/predicate"
	"base-server/internal/data/ent/role"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApiResourcesQuery is the builder for querying ApiResources entities.
type ApiResourcesQuery struct {
	config
	ctx        *QueryContext
	order      []apiresources.OrderOption
	inters     []Interceptor
	predicates []predicate.ApiResources
	withRoles  *RoleQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ApiResourcesQuery builder.
func (arq *ApiResourcesQuery) Where(ps ...predicate.ApiResources) *ApiResourcesQuery {
	arq.predicates = append(arq.predicates, ps...)
	return arq
}

// Limit the number of records to be returned by this query.
func (arq *ApiResourcesQuery) Limit(limit int) *ApiResourcesQuery {
	arq.ctx.Limit = &limit
	return arq
}

// Offset to start from.
func (arq *ApiResourcesQuery) Offset(offset int) *ApiResourcesQuery {
	arq.ctx.Offset = &offset
	return arq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (arq *ApiResourcesQuery) Unique(unique bool) *ApiResourcesQuery {
	arq.ctx.Unique = &unique
	return arq
}

// Order specifies how the records should be ordered.
func (arq *ApiResourcesQuery) Order(o ...apiresources.OrderOption) *ApiResourcesQuery {
	arq.order = append(arq.order, o...)
	return arq
}

// QueryRoles chains the current query on the "roles" edge.
func (arq *ApiResourcesQuery) QueryRoles() *RoleQuery {
	query := (&RoleClient{config: arq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := arq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := arq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(apiresources.Table, apiresources.FieldID, selector),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, apiresources.RolesTable, apiresources.RolesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(arq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ApiResources entity from the query.
// Returns a *NotFoundError when no ApiResources was found.
func (arq *ApiResourcesQuery) First(ctx context.Context) (*ApiResources, error) {
	nodes, err := arq.Limit(1).All(setContextOp(ctx, arq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{apiresources.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (arq *ApiResourcesQuery) FirstX(ctx context.Context) *ApiResources {
	node, err := arq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ApiResources ID from the query.
// Returns a *NotFoundError when no ApiResources ID was found.
func (arq *ApiResourcesQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = arq.Limit(1).IDs(setContextOp(ctx, arq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{apiresources.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (arq *ApiResourcesQuery) FirstIDX(ctx context.Context) string {
	id, err := arq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ApiResources entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ApiResources entity is found.
// Returns a *NotFoundError when no ApiResources entities are found.
func (arq *ApiResourcesQuery) Only(ctx context.Context) (*ApiResources, error) {
	nodes, err := arq.Limit(2).All(setContextOp(ctx, arq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{apiresources.Label}
	default:
		return nil, &NotSingularError{apiresources.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (arq *ApiResourcesQuery) OnlyX(ctx context.Context) *ApiResources {
	node, err := arq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ApiResources ID in the query.
// Returns a *NotSingularError when more than one ApiResources ID is found.
// Returns a *NotFoundError when no entities are found.
func (arq *ApiResourcesQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = arq.Limit(2).IDs(setContextOp(ctx, arq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{apiresources.Label}
	default:
		err = &NotSingularError{apiresources.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (arq *ApiResourcesQuery) OnlyIDX(ctx context.Context) string {
	id, err := arq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ApiResourcesSlice.
func (arq *ApiResourcesQuery) All(ctx context.Context) ([]*ApiResources, error) {
	ctx = setContextOp(ctx, arq.ctx, ent.OpQueryAll)
	if err := arq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ApiResources, *ApiResourcesQuery]()
	return withInterceptors[[]*ApiResources](ctx, arq, qr, arq.inters)
}

// AllX is like All, but panics if an error occurs.
func (arq *ApiResourcesQuery) AllX(ctx context.Context) []*ApiResources {
	nodes, err := arq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ApiResources IDs.
func (arq *ApiResourcesQuery) IDs(ctx context.Context) (ids []string, err error) {
	if arq.ctx.Unique == nil && arq.path != nil {
		arq.Unique(true)
	}
	ctx = setContextOp(ctx, arq.ctx, ent.OpQueryIDs)
	if err = arq.Select(apiresources.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (arq *ApiResourcesQuery) IDsX(ctx context.Context) []string {
	ids, err := arq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (arq *ApiResourcesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, arq.ctx, ent.OpQueryCount)
	if err := arq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, arq, querierCount[*ApiResourcesQuery](), arq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (arq *ApiResourcesQuery) CountX(ctx context.Context) int {
	count, err := arq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (arq *ApiResourcesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, arq.ctx, ent.OpQueryExist)
	switch _, err := arq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (arq *ApiResourcesQuery) ExistX(ctx context.Context) bool {
	exist, err := arq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ApiResourcesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (arq *ApiResourcesQuery) Clone() *ApiResourcesQuery {
	if arq == nil {
		return nil
	}
	return &ApiResourcesQuery{
		config:     arq.config,
		ctx:        arq.ctx.Clone(),
		order:      append([]apiresources.OrderOption{}, arq.order...),
		inters:     append([]Interceptor{}, arq.inters...),
		predicates: append([]predicate.ApiResources{}, arq.predicates...),
		withRoles:  arq.withRoles.Clone(),
		// clone intermediate query.
		sql:       arq.sql.Clone(),
		path:      arq.path,
		modifiers: append([]func(*sql.Selector){}, arq.modifiers...),
	}
}

// WithRoles tells the query-builder to eager-load the nodes that are connected to
// the "roles" edge. The optional arguments are used to configure the query builder of the edge.
func (arq *ApiResourcesQuery) WithRoles(opts ...func(*RoleQuery)) *ApiResourcesQuery {
	query := (&RoleClient{config: arq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	arq.withRoles = query
	return arq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ApiResources.Query().
//		GroupBy(apiresources.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (arq *ApiResourcesQuery) GroupBy(field string, fields ...string) *ApiResourcesGroupBy {
	arq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ApiResourcesGroupBy{build: arq}
	grbuild.flds = &arq.ctx.Fields
	grbuild.label = apiresources.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.ApiResources.Query().
//		Select(apiresources.FieldCreateTime).
//		Scan(ctx, &v)
func (arq *ApiResourcesQuery) Select(fields ...string) *ApiResourcesSelect {
	arq.ctx.Fields = append(arq.ctx.Fields, fields...)
	sbuild := &ApiResourcesSelect{ApiResourcesQuery: arq}
	sbuild.label = apiresources.Label
	sbuild.flds, sbuild.scan = &arq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ApiResourcesSelect configured with the given aggregations.
func (arq *ApiResourcesQuery) Aggregate(fns ...AggregateFunc) *ApiResourcesSelect {
	return arq.Select().Aggregate(fns...)
}

func (arq *ApiResourcesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range arq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, arq); err != nil {
				return err
			}
		}
	}
	for _, f := range arq.ctx.Fields {
		if !apiresources.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if arq.path != nil {
		prev, err := arq.path(ctx)
		if err != nil {
			return err
		}
		arq.sql = prev
	}
	return nil
}

func (arq *ApiResourcesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ApiResources, error) {
	var (
		nodes       = []*ApiResources{}
		_spec       = arq.querySpec()
		loadedTypes = [1]bool{
			arq.withRoles != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ApiResources).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ApiResources{config: arq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(arq.modifiers) > 0 {
		_spec.Modifiers = arq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, arq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := arq.withRoles; query != nil {
		if err := arq.loadRoles(ctx, query, nodes,
			func(n *ApiResources) { n.Edges.Roles = []*Role{} },
			func(n *ApiResources, e *Role) { n.Edges.Roles = append(n.Edges.Roles, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (arq *ApiResourcesQuery) loadRoles(ctx context.Context, query *RoleQuery, nodes []*ApiResources, init func(*ApiResources), assign func(*ApiResources, *Role)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[string]*ApiResources)
	nids := make(map[int64]map[*ApiResources]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(apiresources.RolesTable)
		s.Join(joinT).On(s.C(role.FieldID), joinT.C(apiresources.RolesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(apiresources.RolesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(apiresources.RolesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullString)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullString).String
				inValue := values[1].(*sql.NullInt64).Int64
				if nids[inValue] == nil {
					nids[inValue] = map[*ApiResources]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Role](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "roles" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (arq *ApiResourcesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := arq.querySpec()
	if len(arq.modifiers) > 0 {
		_spec.Modifiers = arq.modifiers
	}
	_spec.Node.Columns = arq.ctx.Fields
	if len(arq.ctx.Fields) > 0 {
		_spec.Unique = arq.ctx.Unique != nil && *arq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, arq.driver, _spec)
}

func (arq *ApiResourcesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(apiresources.Table, apiresources.Columns, sqlgraph.NewFieldSpec(apiresources.FieldID, field.TypeString))
	_spec.From = arq.sql
	if unique := arq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if arq.path != nil {
		_spec.Unique = true
	}
	if fields := arq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apiresources.FieldID)
		for i := range fields {
			if fields[i] != apiresources.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := arq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := arq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := arq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := arq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (arq *ApiResourcesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(arq.driver.Dialect())
	t1 := builder.Table(apiresources.Table)
	columns := arq.ctx.Fields
	if len(columns) == 0 {
		columns = apiresources.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if arq.sql != nil {
		selector = arq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if arq.ctx.Unique != nil && *arq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range arq.modifiers {
		m(selector)
	}
	for _, p := range arq.predicates {
		p(selector)
	}
	for _, p := range arq.order {
		p(selector)
	}
	if offset := arq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := arq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (arq *ApiResourcesQuery) Modify(modifiers ...func(s *sql.Selector)) *ApiResourcesSelect {
	arq.modifiers = append(arq.modifiers, modifiers...)
	return arq.Select()
}

// ApiResourcesGroupBy is the group-by builder for ApiResources entities.
type ApiResourcesGroupBy struct {
	selector
	build *ApiResourcesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (argb *ApiResourcesGroupBy) Aggregate(fns ...AggregateFunc) *ApiResourcesGroupBy {
	argb.fns = append(argb.fns, fns...)
	return argb
}

// Scan applies the selector query and scans the result into the given value.
func (argb *ApiResourcesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, argb.build.ctx, ent.OpQueryGroupBy)
	if err := argb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApiResourcesQuery, *ApiResourcesGroupBy](ctx, argb.build, argb, argb.build.inters, v)
}

func (argb *ApiResourcesGroupBy) sqlScan(ctx context.Context, root *ApiResourcesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(argb.fns))
	for _, fn := range argb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*argb.flds)+len(argb.fns))
		for _, f := range *argb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*argb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := argb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ApiResourcesSelect is the builder for selecting fields of ApiResources entities.
type ApiResourcesSelect struct {
	*ApiResourcesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ars *ApiResourcesSelect) Aggregate(fns ...AggregateFunc) *ApiResourcesSelect {
	ars.fns = append(ars.fns, fns...)
	return ars
}

// Scan applies the selector query and scans the result into the given value.
func (ars *ApiResourcesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ars.ctx, ent.OpQuerySelect)
	if err := ars.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApiResourcesQuery, *ApiResourcesSelect](ctx, ars.ApiResourcesQuery, ars, ars.inters, v)
}

func (ars *ApiResourcesSelect) sqlScan(ctx context.Context, root *ApiResourcesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ars.fns))
	for _, fn := range ars.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ars.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ars.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ars *ApiResourcesSelect) Modify(modifiers ...func(s *sql.Selector)) *ApiResourcesSelect {
	ars.modifiers = append(ars.modifiers, modifiers...)
	return ars
}
