// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.19.1
// source: app/gateway/service/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Protocol int32

const (
	Protocol_UNSPECIFIED Protocol = 0
	Protocol_HTTP        Protocol = 1
	Protocol_GRPC        Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "HTTP",
		2: "GRPC",
	}
	Protocol_value = map[string]int32{
		"UNSPECIFIED": 0,
		"HTTP":        1,
		"GRPC":        2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_app_gateway_service_internal_conf_conf_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_app_gateway_service_internal_conf_conf_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Gateway       *Gateway               `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Services      *Services              `protobuf:"bytes,3,opt,name=services,proto3" json:"services,omitempty"`
	Logger        *Logger                `protobuf:"bytes,4,opt,name=logger,proto3" json:"logger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetGateway() *Gateway {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *Bootstrap) GetServices() *Services {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Bootstrap) GetLogger() *Logger {
	if x != nil {
		return x.Logger
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

type Gateway struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Endpoints     []*Endpoint            `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Middlewares   []*Middleware          `protobuf:"bytes,4,rep,name=middlewares,proto3" json:"middlewares,omitempty"`
	TlsStore      map[string]*TLS        `protobuf:"bytes,5,rep,name=tls_store,json=tlsStore,proto3" json:"tls_store,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gateway) Reset() {
	*x = Gateway{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway) ProtoMessage() {}

func (x *Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway.ProtoReflect.Descriptor instead.
func (*Gateway) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Gateway) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Gateway) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Gateway) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Gateway) GetMiddlewares() []*Middleware {
	if x != nil {
		return x.Middlewares
	}
	return nil
}

func (x *Gateway) GetTlsStore() map[string]*TLS {
	if x != nil {
		return x.TlsStore
	}
	return nil
}

type Services struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Services_Auth         `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Admin         *Services_Admin        `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Services) Reset() {
	*x = Services{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Services) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Services) ProtoMessage() {}

func (x *Services) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Services.ProtoReflect.Descriptor instead.
func (*Services) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Services) GetAuth() *Services_Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Services) GetAdmin() *Services_Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type TLS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Insecure      bool                   `protobuf:"varint,1,opt,name=insecure,proto3" json:"insecure,omitempty"`
	Cacert        string                 `protobuf:"bytes,2,opt,name=cacert,proto3" json:"cacert,omitempty"`
	Cert          string                 `protobuf:"bytes,3,opt,name=cert,proto3" json:"cert,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	ServerName    string                 `protobuf:"bytes,5,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLS) Reset() {
	*x = TLS{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLS) ProtoMessage() {}

func (x *TLS) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLS.ProtoReflect.Descriptor instead.
func (*TLS) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *TLS) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *TLS) GetCacert() string {
	if x != nil {
		return x.Cacert
	}
	return ""
}

func (x *TLS) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *TLS) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TLS) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Protocol      Protocol               `protobuf:"varint,4,opt,name=protocol,proto3,enum=kratos.api.Protocol" json:"protocol,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Middlewares   []*Middleware          `protobuf:"bytes,6,rep,name=middlewares,proto3" json:"middlewares,omitempty"`
	Backends      []*Backend             `protobuf:"bytes,7,rep,name=backends,proto3" json:"backends,omitempty"`
	Retry         *Retry                 `protobuf:"bytes,8,opt,name=retry,proto3" json:"retry,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Host          string                 `protobuf:"bytes,10,opt,name=host,proto3" json:"host,omitempty"`
	Stream        bool                   `protobuf:"varint,11,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Endpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Endpoint) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Endpoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Endpoint) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_UNSPECIFIED
}

func (x *Endpoint) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Endpoint) GetMiddlewares() []*Middleware {
	if x != nil {
		return x.Middlewares
	}
	return nil
}

func (x *Endpoint) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *Endpoint) GetRetry() *Retry {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *Endpoint) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Endpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Endpoint) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type Middleware struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Options       *anypb.Any             `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Middleware) Reset() {
	*x = Middleware{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Middleware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Middleware) ProtoMessage() {}

func (x *Middleware) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Middleware.ProtoReflect.Descriptor instead.
func (*Middleware) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Middleware) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Middleware) GetOptions() *anypb.Any {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Middleware) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type Backend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Weight        *int64                 `protobuf:"varint,2,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	HealthCheck   *HealthCheck           `protobuf:"bytes,3,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Tls           bool                   `protobuf:"varint,4,opt,name=tls,proto3" json:"tls,omitempty"`
	TlsConfigName string                 `protobuf:"bytes,5,opt,name=tls_config_name,json=tlsConfigName,proto3" json:"tls_config_name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Backend) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Backend) GetWeight() int64 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

func (x *Backend) GetHealthCheck() *HealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *Backend) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *Backend) GetTlsConfigName() string {
	if x != nil {
		return x.TlsConfigName
	}
	return ""
}

func (x *Backend) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{8}
}

type Retry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempts      uint32                 `protobuf:"varint,1,opt,name=attempts,proto3" json:"attempts,omitempty"`
	PerTryTimeout *durationpb.Duration   `protobuf:"bytes,2,opt,name=per_try_timeout,json=perTryTimeout,proto3" json:"per_try_timeout,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Priorities    []string               `protobuf:"bytes,4,rep,name=priorities,proto3" json:"priorities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Retry) Reset() {
	*x = Retry{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Retry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Retry) ProtoMessage() {}

func (x *Retry) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Retry.ProtoReflect.Descriptor instead.
func (*Retry) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *Retry) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Retry) GetPerTryTimeout() *durationpb.Duration {
	if x != nil {
		return x.PerTryTimeout
	}
	return nil
}

func (x *Retry) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *Retry) GetPriorities() []string {
	if x != nil {
		return x.Priorities
	}
	return nil
}

type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Condition:
	//
	//	*Condition_ByStatusCode
	//	*Condition_ByHeader
	Condition     isCondition_Condition `protobuf_oneof:"condition"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{10}
}

func (x *Condition) GetCondition() isCondition_Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *Condition) GetByStatusCode() string {
	if x != nil {
		if x, ok := x.Condition.(*Condition_ByStatusCode); ok {
			return x.ByStatusCode
		}
	}
	return ""
}

func (x *Condition) GetByHeader() *Condition_Header {
	if x != nil {
		if x, ok := x.Condition.(*Condition_ByHeader); ok {
			return x.ByHeader
		}
	}
	return nil
}

type isCondition_Condition interface {
	isCondition_Condition()
}

type Condition_ByStatusCode struct {
	ByStatusCode string `protobuf:"bytes,1,opt,name=by_status_code,json=byStatusCode,proto3,oneof"`
}

type Condition_ByHeader struct {
	ByHeader *Condition_Header `protobuf:"bytes,2,opt,name=by_header,json=byHeader,proto3,oneof"`
}

func (*Condition_ByStatusCode) isCondition_Condition() {}

func (*Condition_ByHeader) isCondition_Condition() {}

type Logger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MaxSize       int32                  `protobuf:"varint,3,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MaxBackups    int32                  `protobuf:"varint,4,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	MaxAge        int32                  `protobuf:"varint,5,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	Compress      bool                   `protobuf:"varint,6,opt,name=compress,proto3" json:"compress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logger) Reset() {
	*x = Logger{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logger) ProtoMessage() {}

func (x *Logger) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logger.ProtoReflect.Descriptor instead.
func (*Logger) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{11}
}

func (x *Logger) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Logger) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Logger) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *Logger) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *Logger) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Logger) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

type Server_HTTP struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Network           string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr              string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	ReadHeaderTimeout *durationpb.Duration   `protobuf:"bytes,4,opt,name=read_header_timeout,json=readHeaderTimeout,proto3" json:"read_header_timeout,omitempty"`
	IdleTimeout       *durationpb.Duration   `protobuf:"bytes,5,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Server_HTTP) GetReadHeaderTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadHeaderTimeout
	}
	return nil
}

func (x *Server_HTTP) GetIdleTimeout() *durationpb.Duration {
	if x != nil {
		return x.IdleTimeout
	}
	return nil
}

type Services_Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrpcEndpoint  string                 `protobuf:"bytes,1,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Services_Auth) Reset() {
	*x = Services_Auth{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Services_Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Services_Auth) ProtoMessage() {}

func (x *Services_Auth) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Services_Auth.ProtoReflect.Descriptor instead.
func (*Services_Auth) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Services_Auth) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

type Services_Admin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrpcEndpoint  string                 `protobuf:"bytes,1,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Services_Admin) Reset() {
	*x = Services_Admin{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Services_Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Services_Admin) ProtoMessage() {}

func (x *Services_Admin) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Services_Admin.ProtoReflect.Descriptor instead.
func (*Services_Admin) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Services_Admin) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

type Condition_Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition_Header) Reset() {
	*x = Condition_Header{}
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition_Header) ProtoMessage() {}

func (x *Condition_Header) ProtoReflect() protoreflect.Message {
	mi := &file_app_gateway_service_internal_conf_conf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition_Header.ProtoReflect.Descriptor instead.
func (*Condition_Header) Descriptor() ([]byte, []int) {
	return file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP(), []int{10, 0}
}

func (x *Condition_Header) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Condition_Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_app_gateway_service_internal_conf_conf_proto protoreflect.FileDescriptor

const file_app_gateway_service_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	",app/gateway/service/internal/conf/conf.proto\x12\n" +
	"kratos.api\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\"\xc4\x01\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12-\n" +
	"\agateway\x18\x02 \x01(\v2\x13.kratos.api.GatewayR\agateway\x120\n" +
	"\bservices\x18\x03 \x01(\v2\x14.kratos.api.ServicesR\bservices\x12*\n" +
	"\x06logger\x18\x04 \x01(\v2\x12.kratos.api.LoggerR\x06logger\"\xb3\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x1a\xfb\x01\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12I\n" +
	"\x13read_header_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x11readHeaderTimeout\x12<\n" +
	"\fidle_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vidleTimeout\"\xb3\x02\n" +
	"\aGateway\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x122\n" +
	"\tendpoints\x18\x03 \x03(\v2\x14.kratos.api.EndpointR\tendpoints\x128\n" +
	"\vmiddlewares\x18\x04 \x03(\v2\x16.kratos.api.MiddlewareR\vmiddlewares\x12>\n" +
	"\ttls_store\x18\x05 \x03(\v2!.kratos.api.Gateway.TlsStoreEntryR\btlsStore\x1aL\n" +
	"\rTlsStoreEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.kratos.api.TLSR\x05value:\x028\x01\"\xc6\x01\n" +
	"\bServices\x12-\n" +
	"\x04auth\x18\x01 \x01(\v2\x19.kratos.api.Services.AuthR\x04auth\x120\n" +
	"\x05admin\x18\x02 \x01(\v2\x1a.kratos.api.Services.AdminR\x05admin\x1a+\n" +
	"\x04Auth\x12#\n" +
	"\rgrpc_endpoint\x18\x01 \x01(\tR\fgrpcEndpoint\x1a,\n" +
	"\x05Admin\x12#\n" +
	"\rgrpc_endpoint\x18\x01 \x01(\tR\fgrpcEndpoint\"\x80\x01\n" +
	"\x03TLS\x12\x1a\n" +
	"\binsecure\x18\x01 \x01(\bR\binsecure\x12\x16\n" +
	"\x06cacert\x18\x02 \x01(\tR\x06cacert\x12\x12\n" +
	"\x04cert\x18\x03 \x01(\tR\x04cert\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1f\n" +
	"\vserver_name\x18\x05 \x01(\tR\n" +
	"serverName\"\xfc\x03\n" +
	"\bEndpoint\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x14.kratos.api.ProtocolR\bprotocol\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x128\n" +
	"\vmiddlewares\x18\x06 \x03(\v2\x16.kratos.api.MiddlewareR\vmiddlewares\x12/\n" +
	"\bbackends\x18\a \x03(\v2\x13.kratos.api.BackendR\bbackends\x12'\n" +
	"\x05retry\x18\b \x01(\v2\x11.kratos.api.RetryR\x05retry\x12>\n" +
	"\bmetadata\x18\t \x03(\v2\".kratos.api.Endpoint.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04host\x18\n" +
	" \x01(\tR\x04host\x12\x16\n" +
	"\x06stream\x18\v \x01(\bR\x06stream\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\n" +
	"Middleware\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\aoptions\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\aoptions\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\"\xbb\x02\n" +
	"\aBackend\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1b\n" +
	"\x06weight\x18\x02 \x01(\x03H\x00R\x06weight\x88\x01\x01\x12:\n" +
	"\fhealth_check\x18\x03 \x01(\v2\x17.kratos.api.HealthCheckR\vhealthCheck\x12\x10\n" +
	"\x03tls\x18\x04 \x01(\bR\x03tls\x12&\n" +
	"\x0ftls_config_name\x18\x05 \x01(\tR\rtlsConfigName\x12=\n" +
	"\bmetadata\x18\x06 \x03(\v2!.kratos.api.Backend.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_weight\"\r\n" +
	"\vHealthCheck\"\xbd\x01\n" +
	"\x05Retry\x12\x1a\n" +
	"\battempts\x18\x01 \x01(\rR\battempts\x12A\n" +
	"\x0fper_try_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rperTryTimeout\x125\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2\x15.kratos.api.ConditionR\n" +
	"conditions\x12\x1e\n" +
	"\n" +
	"priorities\x18\x04 \x03(\tR\n" +
	"priorities\"\xb1\x01\n" +
	"\tCondition\x12&\n" +
	"\x0eby_status_code\x18\x01 \x01(\tH\x00R\fbyStatusCode\x12;\n" +
	"\tby_header\x18\x02 \x01(\v2\x1c.kratos.api.Condition.HeaderH\x00R\bbyHeader\x1a2\n" +
	"\x06Header\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueB\v\n" +
	"\tcondition\"\xab\x01\n" +
	"\x06Logger\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x19\n" +
	"\bmax_size\x18\x03 \x01(\x05R\amaxSize\x12\x1f\n" +
	"\vmax_backups\x18\x04 \x01(\x05R\n" +
	"maxBackups\x12\x17\n" +
	"\amax_age\x18\x05 \x01(\x05R\x06maxAge\x12\x1a\n" +
	"\bcompress\x18\x06 \x01(\bR\bcompress*/\n" +
	"\bProtocol\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\b\n" +
	"\x04HTTP\x10\x01\x12\b\n" +
	"\x04GRPC\x10\x02B4Z2base-server/app/gateway/service/internal/conf;confb\x06proto3"

var (
	file_app_gateway_service_internal_conf_conf_proto_rawDescOnce sync.Once
	file_app_gateway_service_internal_conf_conf_proto_rawDescData []byte
)

func file_app_gateway_service_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_app_gateway_service_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_app_gateway_service_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_gateway_service_internal_conf_conf_proto_rawDesc), len(file_app_gateway_service_internal_conf_conf_proto_rawDesc)))
	})
	return file_app_gateway_service_internal_conf_conf_proto_rawDescData
}

var file_app_gateway_service_internal_conf_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_gateway_service_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_app_gateway_service_internal_conf_conf_proto_goTypes = []any{
	(Protocol)(0),               // 0: kratos.api.Protocol
	(*Bootstrap)(nil),           // 1: kratos.api.Bootstrap
	(*Server)(nil),              // 2: kratos.api.Server
	(*Gateway)(nil),             // 3: kratos.api.Gateway
	(*Services)(nil),            // 4: kratos.api.Services
	(*TLS)(nil),                 // 5: kratos.api.TLS
	(*Endpoint)(nil),            // 6: kratos.api.Endpoint
	(*Middleware)(nil),          // 7: kratos.api.Middleware
	(*Backend)(nil),             // 8: kratos.api.Backend
	(*HealthCheck)(nil),         // 9: kratos.api.HealthCheck
	(*Retry)(nil),               // 10: kratos.api.Retry
	(*Condition)(nil),           // 11: kratos.api.Condition
	(*Logger)(nil),              // 12: kratos.api.Logger
	(*Server_HTTP)(nil),         // 13: kratos.api.Server.HTTP
	nil,                         // 14: kratos.api.Gateway.TlsStoreEntry
	(*Services_Auth)(nil),       // 15: kratos.api.Services.Auth
	(*Services_Admin)(nil),      // 16: kratos.api.Services.Admin
	nil,                         // 17: kratos.api.Endpoint.MetadataEntry
	nil,                         // 18: kratos.api.Backend.MetadataEntry
	(*Condition_Header)(nil),    // 19: kratos.api.Condition.Header
	(*durationpb.Duration)(nil), // 20: google.protobuf.Duration
	(*anypb.Any)(nil),           // 21: google.protobuf.Any
}
var file_app_gateway_service_internal_conf_conf_proto_depIdxs = []int32{
	2,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	3,  // 1: kratos.api.Bootstrap.gateway:type_name -> kratos.api.Gateway
	4,  // 2: kratos.api.Bootstrap.services:type_name -> kratos.api.Services
	12, // 3: kratos.api.Bootstrap.logger:type_name -> kratos.api.Logger
	13, // 4: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	6,  // 5: kratos.api.Gateway.endpoints:type_name -> kratos.api.Endpoint
	7,  // 6: kratos.api.Gateway.middlewares:type_name -> kratos.api.Middleware
	14, // 7: kratos.api.Gateway.tls_store:type_name -> kratos.api.Gateway.TlsStoreEntry
	15, // 8: kratos.api.Services.auth:type_name -> kratos.api.Services.Auth
	16, // 9: kratos.api.Services.admin:type_name -> kratos.api.Services.Admin
	0,  // 10: kratos.api.Endpoint.protocol:type_name -> kratos.api.Protocol
	20, // 11: kratos.api.Endpoint.timeout:type_name -> google.protobuf.Duration
	7,  // 12: kratos.api.Endpoint.middlewares:type_name -> kratos.api.Middleware
	8,  // 13: kratos.api.Endpoint.backends:type_name -> kratos.api.Backend
	10, // 14: kratos.api.Endpoint.retry:type_name -> kratos.api.Retry
	17, // 15: kratos.api.Endpoint.metadata:type_name -> kratos.api.Endpoint.MetadataEntry
	21, // 16: kratos.api.Middleware.options:type_name -> google.protobuf.Any
	9,  // 17: kratos.api.Backend.health_check:type_name -> kratos.api.HealthCheck
	18, // 18: kratos.api.Backend.metadata:type_name -> kratos.api.Backend.MetadataEntry
	20, // 19: kratos.api.Retry.per_try_timeout:type_name -> google.protobuf.Duration
	11, // 20: kratos.api.Retry.conditions:type_name -> kratos.api.Condition
	19, // 21: kratos.api.Condition.by_header:type_name -> kratos.api.Condition.Header
	20, // 22: kratos.api.Server.HTTP.read_timeout:type_name -> google.protobuf.Duration
	20, // 23: kratos.api.Server.HTTP.read_header_timeout:type_name -> google.protobuf.Duration
	20, // 24: kratos.api.Server.HTTP.idle_timeout:type_name -> google.protobuf.Duration
	5,  // 25: kratos.api.Gateway.TlsStoreEntry.value:type_name -> kratos.api.TLS
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_app_gateway_service_internal_conf_conf_proto_init() }
func file_app_gateway_service_internal_conf_conf_proto_init() {
	if File_app_gateway_service_internal_conf_conf_proto != nil {
		return
	}
	file_app_gateway_service_internal_conf_conf_proto_msgTypes[7].OneofWrappers = []any{}
	file_app_gateway_service_internal_conf_conf_proto_msgTypes[10].OneofWrappers = []any{
		(*Condition_ByStatusCode)(nil),
		(*Condition_ByHeader)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_gateway_service_internal_conf_conf_proto_rawDesc), len(file_app_gateway_service_internal_conf_conf_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_gateway_service_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_app_gateway_service_internal_conf_conf_proto_depIdxs,
		EnumInfos:         file_app_gateway_service_internal_conf_conf_proto_enumTypes,
		MessageInfos:      file_app_gateway_service_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_app_gateway_service_internal_conf_conf_proto = out.File
	file_app_gateway_service_internal_conf_conf_proto_goTypes = nil
	file_app_gateway_service_internal_conf_conf_proto_depIdxs = nil
}
