// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-server/pkg/data/ent/organizationpermissionscope"
	"base-server/pkg/data/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrganizationPermissionScopeUpdate is the builder for updating OrganizationPermissionScope entities.
type OrganizationPermissionScopeUpdate struct {
	config
	hooks     []Hook
	mutation  *OrganizationPermissionScopeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OrganizationPermissionScopeUpdate builder.
func (_u *OrganizationPermissionScopeUpdate) Where(ps ...predicate.OrganizationPermissionScope) *OrganizationPermissionScopeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *OrganizationPermissionScopeUpdate) SetUpdateTime(v time.Time) *OrganizationPermissionScopeUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *OrganizationPermissionScopeUpdate) SetOrganizationID(v string) *OrganizationPermissionScopeUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *OrganizationPermissionScopeUpdate) SetNillableOrganizationID(v *string) *OrganizationPermissionScopeUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetPermissionType sets the "permission_type" field.
func (_u *OrganizationPermissionScopeUpdate) SetPermissionType(v string) *OrganizationPermissionScopeUpdate {
	_u.mutation.SetPermissionType(v)
	return _u
}

// SetNillablePermissionType sets the "permission_type" field if the given value is not nil.
func (_u *OrganizationPermissionScopeUpdate) SetNillablePermissionType(v *string) *OrganizationPermissionScopeUpdate {
	if v != nil {
		_u.SetPermissionType(*v)
	}
	return _u
}

// SetPermissionRef sets the "permission_ref" field.
func (_u *OrganizationPermissionScopeUpdate) SetPermissionRef(v string) *OrganizationPermissionScopeUpdate {
	_u.mutation.SetPermissionRef(v)
	return _u
}

// SetNillablePermissionRef sets the "permission_ref" field if the given value is not nil.
func (_u *OrganizationPermissionScopeUpdate) SetNillablePermissionRef(v *string) *OrganizationPermissionScopeUpdate {
	if v != nil {
		_u.SetPermissionRef(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *OrganizationPermissionScopeUpdate) SetCreatedBy(v string) *OrganizationPermissionScopeUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *OrganizationPermissionScopeUpdate) SetNillableCreatedBy(v *string) *OrganizationPermissionScopeUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// Mutation returns the OrganizationPermissionScopeMutation object of the builder.
func (_u *OrganizationPermissionScopeUpdate) Mutation() *OrganizationPermissionScopeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrganizationPermissionScopeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationPermissionScopeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrganizationPermissionScopeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationPermissionScopeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrganizationPermissionScopeUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := organizationpermissionscope.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OrganizationPermissionScopeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrganizationPermissionScopeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OrganizationPermissionScopeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(organizationpermissionscope.Table, organizationpermissionscope.Columns, sqlgraph.NewFieldSpec(organizationpermissionscope.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(organizationpermissionscope.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(organizationpermissionscope.FieldOrganizationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermissionType(); ok {
		_spec.SetField(organizationpermissionscope.FieldPermissionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermissionRef(); ok {
		_spec.SetField(organizationpermissionscope.FieldPermissionRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(organizationpermissionscope.FieldCreatedBy, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationpermissionscope.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrganizationPermissionScopeUpdateOne is the builder for updating a single OrganizationPermissionScope entity.
type OrganizationPermissionScopeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OrganizationPermissionScopeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *OrganizationPermissionScopeUpdateOne) SetUpdateTime(v time.Time) *OrganizationPermissionScopeUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *OrganizationPermissionScopeUpdateOne) SetOrganizationID(v string) *OrganizationPermissionScopeUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *OrganizationPermissionScopeUpdateOne) SetNillableOrganizationID(v *string) *OrganizationPermissionScopeUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetPermissionType sets the "permission_type" field.
func (_u *OrganizationPermissionScopeUpdateOne) SetPermissionType(v string) *OrganizationPermissionScopeUpdateOne {
	_u.mutation.SetPermissionType(v)
	return _u
}

// SetNillablePermissionType sets the "permission_type" field if the given value is not nil.
func (_u *OrganizationPermissionScopeUpdateOne) SetNillablePermissionType(v *string) *OrganizationPermissionScopeUpdateOne {
	if v != nil {
		_u.SetPermissionType(*v)
	}
	return _u
}

// SetPermissionRef sets the "permission_ref" field.
func (_u *OrganizationPermissionScopeUpdateOne) SetPermissionRef(v string) *OrganizationPermissionScopeUpdateOne {
	_u.mutation.SetPermissionRef(v)
	return _u
}

// SetNillablePermissionRef sets the "permission_ref" field if the given value is not nil.
func (_u *OrganizationPermissionScopeUpdateOne) SetNillablePermissionRef(v *string) *OrganizationPermissionScopeUpdateOne {
	if v != nil {
		_u.SetPermissionRef(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *OrganizationPermissionScopeUpdateOne) SetCreatedBy(v string) *OrganizationPermissionScopeUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *OrganizationPermissionScopeUpdateOne) SetNillableCreatedBy(v *string) *OrganizationPermissionScopeUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// Mutation returns the OrganizationPermissionScopeMutation object of the builder.
func (_u *OrganizationPermissionScopeUpdateOne) Mutation() *OrganizationPermissionScopeMutation {
	return _u.mutation
}

// Where appends a list predicates to the OrganizationPermissionScopeUpdate builder.
func (_u *OrganizationPermissionScopeUpdateOne) Where(ps ...predicate.OrganizationPermissionScope) *OrganizationPermissionScopeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrganizationPermissionScopeUpdateOne) Select(field string, fields ...string) *OrganizationPermissionScopeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrganizationPermissionScope entity.
func (_u *OrganizationPermissionScopeUpdateOne) Save(ctx context.Context) (*OrganizationPermissionScope, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationPermissionScopeUpdateOne) SaveX(ctx context.Context) *OrganizationPermissionScope {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrganizationPermissionScopeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationPermissionScopeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrganizationPermissionScopeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := organizationpermissionscope.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OrganizationPermissionScopeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrganizationPermissionScopeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OrganizationPermissionScopeUpdateOne) sqlSave(ctx context.Context) (_node *OrganizationPermissionScope, err error) {
	_spec := sqlgraph.NewUpdateSpec(organizationpermissionscope.Table, organizationpermissionscope.Columns, sqlgraph.NewFieldSpec(organizationpermissionscope.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrganizationPermissionScope.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organizationpermissionscope.FieldID)
		for _, f := range fields {
			if !organizationpermissionscope.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organizationpermissionscope.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(organizationpermissionscope.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(organizationpermissionscope.FieldOrganizationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermissionType(); ok {
		_spec.SetField(organizationpermissionscope.FieldPermissionType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermissionRef(); ok {
		_spec.SetField(organizationpermissionscope.FieldPermissionRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(organizationpermissionscope.FieldCreatedBy, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &OrganizationPermissionScope{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationpermissionscope.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
