// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-server/pkg/data/ent/predicate"
	"base-server/pkg/data/ent/userrolebinding"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserRoleBindingDelete is the builder for deleting a UserRoleBinding entity.
type UserRoleBindingDelete struct {
	config
	hooks    []Hook
	mutation *UserRoleBindingMutation
}

// Where appends a list predicates to the UserRoleBindingDelete builder.
func (_d *UserRoleBindingDelete) Where(ps ...predicate.UserRoleBinding) *UserRoleBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserRoleBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserRoleBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserRoleBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userrolebinding.Table, sqlgraph.NewFieldSpec(userrolebinding.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserRoleBindingDeleteOne is the builder for deleting a single UserRoleBinding entity.
type UserRoleBindingDeleteOne struct {
	_d *UserRoleBindingDelete
}

// Where appends a list predicates to the UserRoleBindingDelete builder.
func (_d *UserRoleBindingDeleteOne) Where(ps ...predicate.UserRoleBinding) *UserRoleBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserRoleBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userrolebinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserRoleBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
