// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-server/pkg/data/ent/predicate"
	"base-server/pkg/data/ent/userdeptmembership"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserDeptMembershipUpdate is the builder for updating UserDeptMembership entities.
type UserDeptMembershipUpdate struct {
	config
	hooks     []Hook
	mutation  *UserDeptMembershipMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserDeptMembershipUpdate builder.
func (_u *UserDeptMembershipUpdate) Where(ps ...predicate.UserDeptMembership) *UserDeptMembershipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserDeptMembershipUpdate) SetUpdateTime(v time.Time) *UserDeptMembershipUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserDeptMembershipUpdate) SetUserID(v string) *UserDeptMembershipUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserDeptMembershipUpdate) SetNillableUserID(v *string) *UserDeptMembershipUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDeptID sets the "dept_id" field.
func (_u *UserDeptMembershipUpdate) SetDeptID(v int64) *UserDeptMembershipUpdate {
	_u.mutation.ResetDeptID()
	_u.mutation.SetDeptID(v)
	return _u
}

// SetNillableDeptID sets the "dept_id" field if the given value is not nil.
func (_u *UserDeptMembershipUpdate) SetNillableDeptID(v *int64) *UserDeptMembershipUpdate {
	if v != nil {
		_u.SetDeptID(*v)
	}
	return _u
}

// AddDeptID adds value to the "dept_id" field.
func (_u *UserDeptMembershipUpdate) AddDeptID(v int64) *UserDeptMembershipUpdate {
	_u.mutation.AddDeptID(v)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *UserDeptMembershipUpdate) SetOrganizationID(v string) *UserDeptMembershipUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *UserDeptMembershipUpdate) SetNillableOrganizationID(v *string) *UserDeptMembershipUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// Mutation returns the UserDeptMembershipMutation object of the builder.
func (_u *UserDeptMembershipUpdate) Mutation() *UserDeptMembershipMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserDeptMembershipUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserDeptMembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserDeptMembershipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserDeptMembershipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserDeptMembershipUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := userdeptmembership.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserDeptMembershipUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserDeptMembershipUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserDeptMembershipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userdeptmembership.Table, userdeptmembership.Columns, sqlgraph.NewFieldSpec(userdeptmembership.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(userdeptmembership.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userdeptmembership.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeptID(); ok {
		_spec.SetField(userdeptmembership.FieldDeptID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeptID(); ok {
		_spec.AddField(userdeptmembership.FieldDeptID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(userdeptmembership.FieldOrganizationID, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userdeptmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserDeptMembershipUpdateOne is the builder for updating a single UserDeptMembership entity.
type UserDeptMembershipUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserDeptMembershipMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserDeptMembershipUpdateOne) SetUpdateTime(v time.Time) *UserDeptMembershipUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserDeptMembershipUpdateOne) SetUserID(v string) *UserDeptMembershipUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserDeptMembershipUpdateOne) SetNillableUserID(v *string) *UserDeptMembershipUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetDeptID sets the "dept_id" field.
func (_u *UserDeptMembershipUpdateOne) SetDeptID(v int64) *UserDeptMembershipUpdateOne {
	_u.mutation.ResetDeptID()
	_u.mutation.SetDeptID(v)
	return _u
}

// SetNillableDeptID sets the "dept_id" field if the given value is not nil.
func (_u *UserDeptMembershipUpdateOne) SetNillableDeptID(v *int64) *UserDeptMembershipUpdateOne {
	if v != nil {
		_u.SetDeptID(*v)
	}
	return _u
}

// AddDeptID adds value to the "dept_id" field.
func (_u *UserDeptMembershipUpdateOne) AddDeptID(v int64) *UserDeptMembershipUpdateOne {
	_u.mutation.AddDeptID(v)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *UserDeptMembershipUpdateOne) SetOrganizationID(v string) *UserDeptMembershipUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *UserDeptMembershipUpdateOne) SetNillableOrganizationID(v *string) *UserDeptMembershipUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// Mutation returns the UserDeptMembershipMutation object of the builder.
func (_u *UserDeptMembershipUpdateOne) Mutation() *UserDeptMembershipMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserDeptMembershipUpdate builder.
func (_u *UserDeptMembershipUpdateOne) Where(ps ...predicate.UserDeptMembership) *UserDeptMembershipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserDeptMembershipUpdateOne) Select(field string, fields ...string) *UserDeptMembershipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserDeptMembership entity.
func (_u *UserDeptMembershipUpdateOne) Save(ctx context.Context) (*UserDeptMembership, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserDeptMembershipUpdateOne) SaveX(ctx context.Context) *UserDeptMembership {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserDeptMembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserDeptMembershipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserDeptMembershipUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := userdeptmembership.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserDeptMembershipUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserDeptMembershipUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserDeptMembershipUpdateOne) sqlSave(ctx context.Context) (_node *UserDeptMembership, err error) {
	_spec := sqlgraph.NewUpdateSpec(userdeptmembership.Table, userdeptmembership.Columns, sqlgraph.NewFieldSpec(userdeptmembership.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserDeptMembership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userdeptmembership.FieldID)
		for _, f := range fields {
			if !userdeptmembership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userdeptmembership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(userdeptmembership.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(userdeptmembership.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeptID(); ok {
		_spec.SetField(userdeptmembership.FieldDeptID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeptID(); ok {
		_spec.AddField(userdeptmembership.FieldDeptID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(userdeptmembership.FieldOrganizationID, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UserDeptMembership{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userdeptmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
