// Code generated by ent, DO NOT EDIT.

package ent

import (
	"base-server/pkg/data/ent/predicate"
	"base-server/pkg/data/ent/userdeptmembership"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserDeptMembershipDelete is the builder for deleting a UserDeptMembership entity.
type UserDeptMembershipDelete struct {
	config
	hooks    []Hook
	mutation *UserDeptMembershipMutation
}

// Where appends a list predicates to the UserDeptMembershipDelete builder.
func (_d *UserDeptMembershipDelete) Where(ps ...predicate.UserDeptMembership) *UserDeptMembershipDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserDeptMembershipDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserDeptMembershipDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserDeptMembershipDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userdeptmembership.Table, sqlgraph.NewFieldSpec(userdeptmembership.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserDeptMembershipDeleteOne is the builder for deleting a single UserDeptMembership entity.
type UserDeptMembershipDeleteOne struct {
	_d *UserDeptMembershipDelete
}

// Where appends a list predicates to the UserDeptMembershipDelete builder.
func (_d *UserDeptMembershipDeleteOne) Where(ps ...predicate.UserDeptMembership) *UserDeptMembershipDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserDeptMembershipDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userdeptmembership.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserDeptMembershipDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
