// Code generated by ent, DO NOT EDIT.

package projectionsourcestatus

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the projectionsourcestatus type in the database.
	Label = "projection_source_status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldSourceService holds the string denoting the source_service field in the database.
	FieldSourceService = "source_service"
	// FieldDomainCode holds the string denoting the domain_code field in the database.
	FieldDomainCode = "domain_code"
	// FieldSyncMode holds the string denoting the sync_mode field in the database.
	FieldSyncMode = "sync_mode"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldLastSnapshotRevision holds the string denoting the last_snapshot_revision field in the database.
	FieldLastSnapshotRevision = "last_snapshot_revision"
	// FieldLastSyncTime holds the string denoting the last_sync_time field in the database.
	FieldLastSyncTime = "last_sync_time"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// Table holds the table name of the projectionsourcestatus in the database.
	Table = "sys_projection_source_status"
)

// Columns holds all SQL columns for projectionsourcestatus fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldSourceService,
	FieldDomainCode,
	FieldSyncMode,
	FieldState,
	FieldLastSnapshotRevision,
	FieldLastSyncTime,
	FieldLastError,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultDomainCode holds the default value on creation for the "domain_code" field.
	DefaultDomainCode string
	// DefaultSyncMode holds the default value on creation for the "sync_mode" field.
	DefaultSyncMode string
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState string
	// DefaultLastSnapshotRevision holds the default value on creation for the "last_snapshot_revision" field.
	DefaultLastSnapshotRevision uint64
	// DefaultLastSyncTime holds the default value on creation for the "last_sync_time" field.
	DefaultLastSyncTime string
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the ProjectionSourceStatus queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// BySourceService orders the results by the source_service field.
func BySourceService(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceService, opts...).ToFunc()
}

// ByDomainCode orders the results by the domain_code field.
func ByDomainCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomainCode, opts...).ToFunc()
}

// BySyncMode orders the results by the sync_mode field.
func BySyncMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncMode, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByLastSnapshotRevision orders the results by the last_snapshot_revision field.
func ByLastSnapshotRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSnapshotRevision, opts...).ToFunc()
}

// ByLastSyncTime orders the results by the last_sync_time field.
func ByLastSyncTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncTime, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}
