// Code generated by ent, DO NOT EDIT.

package projectionsourcestatus

import (
	"base-server/pkg/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContainsFold(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldUpdateTime, v))
}

// SourceService applies equality check predicate on the "source_service" field. It's identical to SourceServiceEQ.
func SourceService(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldSourceService, v))
}

// SyncMode applies equality check predicate on the "sync_mode" field. It's identical to SyncModeEQ.
func SyncMode(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldSyncMode, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldState, v))
}

// LastSnapshotRevision applies equality check predicate on the "last_snapshot_revision" field. It's identical to LastSnapshotRevisionEQ.
func LastSnapshotRevision(v uint64) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldLastSnapshotRevision, v))
}

// LastSyncTime applies equality check predicate on the "last_sync_time" field. It's identical to LastSyncTimeEQ.
func LastSyncTime(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldLastSyncTime, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldLastError, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldDescription, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLTE(FieldUpdateTime, v))
}

// SourceServiceEQ applies the EQ predicate on the "source_service" field.
func SourceServiceEQ(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldSourceService, v))
}

// SourceServiceNEQ applies the NEQ predicate on the "source_service" field.
func SourceServiceNEQ(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNEQ(FieldSourceService, v))
}

// SourceServiceIn applies the In predicate on the "source_service" field.
func SourceServiceIn(vs ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldIn(FieldSourceService, vs...))
}

// SourceServiceNotIn applies the NotIn predicate on the "source_service" field.
func SourceServiceNotIn(vs ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNotIn(FieldSourceService, vs...))
}

// SourceServiceGT applies the GT predicate on the "source_service" field.
func SourceServiceGT(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGT(FieldSourceService, v))
}

// SourceServiceGTE applies the GTE predicate on the "source_service" field.
func SourceServiceGTE(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGTE(FieldSourceService, v))
}

// SourceServiceLT applies the LT predicate on the "source_service" field.
func SourceServiceLT(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLT(FieldSourceService, v))
}

// SourceServiceLTE applies the LTE predicate on the "source_service" field.
func SourceServiceLTE(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLTE(FieldSourceService, v))
}

// SourceServiceContains applies the Contains predicate on the "source_service" field.
func SourceServiceContains(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContains(FieldSourceService, v))
}

// SourceServiceHasPrefix applies the HasPrefix predicate on the "source_service" field.
func SourceServiceHasPrefix(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldHasPrefix(FieldSourceService, v))
}

// SourceServiceHasSuffix applies the HasSuffix predicate on the "source_service" field.
func SourceServiceHasSuffix(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldHasSuffix(FieldSourceService, v))
}

// SourceServiceEqualFold applies the EqualFold predicate on the "source_service" field.
func SourceServiceEqualFold(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEqualFold(FieldSourceService, v))
}

// SourceServiceContainsFold applies the ContainsFold predicate on the "source_service" field.
func SourceServiceContainsFold(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContainsFold(FieldSourceService, v))
}

// SyncModeEQ applies the EQ predicate on the "sync_mode" field.
func SyncModeEQ(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldSyncMode, v))
}

// SyncModeNEQ applies the NEQ predicate on the "sync_mode" field.
func SyncModeNEQ(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNEQ(FieldSyncMode, v))
}

// SyncModeIn applies the In predicate on the "sync_mode" field.
func SyncModeIn(vs ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldIn(FieldSyncMode, vs...))
}

// SyncModeNotIn applies the NotIn predicate on the "sync_mode" field.
func SyncModeNotIn(vs ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNotIn(FieldSyncMode, vs...))
}

// SyncModeGT applies the GT predicate on the "sync_mode" field.
func SyncModeGT(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGT(FieldSyncMode, v))
}

// SyncModeGTE applies the GTE predicate on the "sync_mode" field.
func SyncModeGTE(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGTE(FieldSyncMode, v))
}

// SyncModeLT applies the LT predicate on the "sync_mode" field.
func SyncModeLT(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLT(FieldSyncMode, v))
}

// SyncModeLTE applies the LTE predicate on the "sync_mode" field.
func SyncModeLTE(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLTE(FieldSyncMode, v))
}

// SyncModeContains applies the Contains predicate on the "sync_mode" field.
func SyncModeContains(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContains(FieldSyncMode, v))
}

// SyncModeHasPrefix applies the HasPrefix predicate on the "sync_mode" field.
func SyncModeHasPrefix(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldHasPrefix(FieldSyncMode, v))
}

// SyncModeHasSuffix applies the HasSuffix predicate on the "sync_mode" field.
func SyncModeHasSuffix(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldHasSuffix(FieldSyncMode, v))
}

// SyncModeEqualFold applies the EqualFold predicate on the "sync_mode" field.
func SyncModeEqualFold(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEqualFold(FieldSyncMode, v))
}

// SyncModeContainsFold applies the ContainsFold predicate on the "sync_mode" field.
func SyncModeContainsFold(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContainsFold(FieldSyncMode, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContainsFold(FieldState, v))
}

// LastSnapshotRevisionEQ applies the EQ predicate on the "last_snapshot_revision" field.
func LastSnapshotRevisionEQ(v uint64) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldLastSnapshotRevision, v))
}

// LastSnapshotRevisionNEQ applies the NEQ predicate on the "last_snapshot_revision" field.
func LastSnapshotRevisionNEQ(v uint64) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNEQ(FieldLastSnapshotRevision, v))
}

// LastSnapshotRevisionIn applies the In predicate on the "last_snapshot_revision" field.
func LastSnapshotRevisionIn(vs ...uint64) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldIn(FieldLastSnapshotRevision, vs...))
}

// LastSnapshotRevisionNotIn applies the NotIn predicate on the "last_snapshot_revision" field.
func LastSnapshotRevisionNotIn(vs ...uint64) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNotIn(FieldLastSnapshotRevision, vs...))
}

// LastSnapshotRevisionGT applies the GT predicate on the "last_snapshot_revision" field.
func LastSnapshotRevisionGT(v uint64) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGT(FieldLastSnapshotRevision, v))
}

// LastSnapshotRevisionGTE applies the GTE predicate on the "last_snapshot_revision" field.
func LastSnapshotRevisionGTE(v uint64) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGTE(FieldLastSnapshotRevision, v))
}

// LastSnapshotRevisionLT applies the LT predicate on the "last_snapshot_revision" field.
func LastSnapshotRevisionLT(v uint64) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLT(FieldLastSnapshotRevision, v))
}

// LastSnapshotRevisionLTE applies the LTE predicate on the "last_snapshot_revision" field.
func LastSnapshotRevisionLTE(v uint64) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLTE(FieldLastSnapshotRevision, v))
}

// LastSyncTimeEQ applies the EQ predicate on the "last_sync_time" field.
func LastSyncTimeEQ(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldLastSyncTime, v))
}

// LastSyncTimeNEQ applies the NEQ predicate on the "last_sync_time" field.
func LastSyncTimeNEQ(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNEQ(FieldLastSyncTime, v))
}

// LastSyncTimeIn applies the In predicate on the "last_sync_time" field.
func LastSyncTimeIn(vs ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldIn(FieldLastSyncTime, vs...))
}

// LastSyncTimeNotIn applies the NotIn predicate on the "last_sync_time" field.
func LastSyncTimeNotIn(vs ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNotIn(FieldLastSyncTime, vs...))
}

// LastSyncTimeGT applies the GT predicate on the "last_sync_time" field.
func LastSyncTimeGT(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGT(FieldLastSyncTime, v))
}

// LastSyncTimeGTE applies the GTE predicate on the "last_sync_time" field.
func LastSyncTimeGTE(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGTE(FieldLastSyncTime, v))
}

// LastSyncTimeLT applies the LT predicate on the "last_sync_time" field.
func LastSyncTimeLT(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLT(FieldLastSyncTime, v))
}

// LastSyncTimeLTE applies the LTE predicate on the "last_sync_time" field.
func LastSyncTimeLTE(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLTE(FieldLastSyncTime, v))
}

// LastSyncTimeContains applies the Contains predicate on the "last_sync_time" field.
func LastSyncTimeContains(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContains(FieldLastSyncTime, v))
}

// LastSyncTimeHasPrefix applies the HasPrefix predicate on the "last_sync_time" field.
func LastSyncTimeHasPrefix(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldHasPrefix(FieldLastSyncTime, v))
}

// LastSyncTimeHasSuffix applies the HasSuffix predicate on the "last_sync_time" field.
func LastSyncTimeHasSuffix(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldHasSuffix(FieldLastSyncTime, v))
}

// LastSyncTimeEqualFold applies the EqualFold predicate on the "last_sync_time" field.
func LastSyncTimeEqualFold(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEqualFold(FieldLastSyncTime, v))
}

// LastSyncTimeContainsFold applies the ContainsFold predicate on the "last_sync_time" field.
func LastSyncTimeContainsFold(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContainsFold(FieldLastSyncTime, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContainsFold(FieldLastError, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.FieldContainsFold(FieldDescription, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProjectionSourceStatus) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProjectionSourceStatus) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProjectionSourceStatus) predicate.ProjectionSourceStatus {
	return predicate.ProjectionSourceStatus(sql.NotPredicates(p))
}
