// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysAPIResourcesColumns holds the columns for the "sys_api_resources" table.
	SysAPIResourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "数据唯一标识"},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString, Comment: "描述"},
		{Name: "path", Type: field.TypeString, Comment: "路径"},
		{Name: "method", Type: field.TypeString, Comment: "方法"},
		{Name: "module", Type: field.TypeString, Comment: "模块"},
		{Name: "module_description", Type: field.TypeString, Comment: "模块描述"},
		{Name: "resources_group", Type: field.TypeString, Comment: "资源组"},
		{Name: "service_code", Type: field.TypeString, Comment: "归属服务编码", Default: ""},
		{Name: "domain_code", Type: field.TypeString, Comment: "归属业务域编码", Default: ""},
	}
	// SysAPIResourcesTable holds the schema information for the "sys_api_resources" table.
	SysAPIResourcesTable = &schema.Table{
		Name:       "sys_api_resources",
		Comment:    "系统API表",
		Columns:    SysAPIResourcesColumns,
		PrimaryKey: []*schema.Column{SysAPIResourcesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "apiresources_path_method",
				Unique:  true,
				Columns: []*schema.Column{SysAPIResourcesColumns[4], SysAPIResourcesColumns[5]},
			},
		},
	}
	// SysBusinessDomainColumns holds the columns for the "sys_business_domain" table.
	SysBusinessDomainColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "数据唯一标识"},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "code", Type: field.TypeString, Unique: true, Comment: "业务域编码"},
		{Name: "name", Type: field.TypeString, Comment: "业务域名称"},
		{Name: "owner_service", Type: field.TypeString, Comment: "主服务编码"},
		{Name: "org_model_type", Type: field.TypeString, Comment: "组织模型类型"},
		{Name: "auth_scope_type", Type: field.TypeString, Comment: "权限范围类型"},
		{Name: "status", Type: field.TypeBool, Comment: "0-禁用，1-启用", Default: true},
		{Name: "description", Type: field.TypeString, Comment: "描述", Default: ""},
		{Name: "meta_json", Type: field.TypeString, Comment: "扩展元数据", Default: ""},
	}
	// SysBusinessDomainTable holds the schema information for the "sys_business_domain" table.
	SysBusinessDomainTable = &schema.Table{
		Name:       "sys_business_domain",
		Comment:    "平台业务域注册表",
		Columns:    SysBusinessDomainColumns,
		PrimaryKey: []*schema.Column{SysBusinessDomainColumns[0]},
	}
	// SysDeptColumns holds the columns for the "sys_dept" table.
	SysDeptColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Comment: "部门名称"},
		{Name: "sort", Type: field.TypeInt32, Comment: "排序"},
		{Name: "status", Type: field.TypeBool, Comment: "0-锁定，1-正常"},
		{Name: "desc", Type: field.TypeString, Comment: "备注"},
		{Name: "extension", Type: field.TypeString, Comment: "扩展信息"},
		{Name: "dom", Type: field.TypeInt64, Comment: "域"},
		{Name: "pid", Type: field.TypeInt64, Nullable: true, Comment: "父节点id"},
	}
	// SysDeptTable holds the schema information for the "sys_dept" table.
	SysDeptTable = &schema.Table{
		Name:       "sys_dept",
		Comment:    "部门表",
		Columns:    SysDeptColumns,
		PrimaryKey: []*schema.Column{SysDeptColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_dept_sys_dept_children",
				Columns:    []*schema.Column{SysDeptColumns[9]},
				RefColumns: []*schema.Column{SysDeptColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SysMenuColumns holds the columns for the "sys_menu" table.
	SysMenuColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "pid", Type: field.TypeInt64, Comment: "上一级ID"},
		{Name: "type", Type: field.TypeString, Comment: "菜单类型,catalog-目录，menu-菜单，embedded-内嵌，link-外链，button-按钮"},
		{Name: "status", Type: field.TypeBool, Comment: "状态,0-禁用，1-启用", Default: false},
		{Name: "path", Type: field.TypeString, Comment: "路由path"},
		{Name: "redirect", Type: field.TypeString, Comment: "重定向path", Default: ""},
		{Name: "alias", Type: field.TypeString, Comment: "记录的别名，例如/users/:id和/u/:id。所有alias和path值必须共享相同的参数。", Default: ""},
		{Name: "name", Type: field.TypeString, Comment: "组件名"},
		{Name: "component", Type: field.TypeString, Comment: "组件路径"},
		{Name: "icon", Type: field.TypeString, Comment: "图标", Default: ""},
		{Name: "title", Type: field.TypeString, Comment: "显示名称"},
		{Name: "order", Type: field.TypeInt32, Comment: "排序(越小越前)", Default: 0},
		{Name: "open_in_new_window", Type: field.TypeBool, Comment: "在新窗口打开", Default: false},
		{Name: "no_basic_layout", Type: field.TypeBool, Comment: "不使用基础布局（仅在顶级生效）", Default: false},
		{Name: "menu_visible_with_forbidden", Type: field.TypeBool, Comment: "菜单可以看到，但是访问会被重定向到403", Default: false},
		{Name: "link", Type: field.TypeString, Comment: "外链-跳转路径", Default: ""},
		{Name: "iframe_src", Type: field.TypeString, Comment: "iframe地址", Default: ""},
		{Name: "active_icon", Type: field.TypeString, Comment: "激活图标（菜单）", Default: ""},
		{Name: "active_path", Type: field.TypeString, Comment: "当前激活的菜单，有时候不想激活现有菜单，需要激活父级菜单时使用", Default: ""},
		{Name: "max_num_of_open_tab", Type: field.TypeInt16, Comment: "标签页最大打开数量", Default: -1},
		{Name: "keepalive", Type: field.TypeBool, Comment: "缓存,0-否，1-是", Default: false},
		{Name: "ignore_access", Type: field.TypeBool, Comment: "忽略权限，直接可以访问", Default: false},
		{Name: "authority", Type: field.TypeString, Comment: "需要特定的角色标识才可以访问(数组，','分割)", Default: ""},
		{Name: "affix_tab", Type: field.TypeBool, Comment: "是否固定标签页,0-否，1-是", Default: false},
		{Name: "affix_tab_order", Type: field.TypeInt16, Comment: "固定标签页的顺序", Default: 0},
		{Name: "hide_in_menu", Type: field.TypeBool, Comment: "当前路由在菜单中不展现,0-否，1-是", Default: false},
		{Name: "hide_in_tab", Type: field.TypeBool, Comment: "当前路由在标签页不展现,0-否，1-是", Default: false},
		{Name: "hide_in_breadcrumb", Type: field.TypeBool, Comment: "当前路由在面包屑中不展现,0-否，1-是", Default: false},
		{Name: "hide_children_in_menu", Type: field.TypeBool, Comment: "当前路由的子级在菜单中不展现,0-否，1-是", Default: false},
		{Name: "full_path_key", Type: field.TypeBool, Comment: "路由的完整路径作为key（默认true）", Default: true},
		{Name: "badge", Type: field.TypeString, Comment: "用于配置页面的徽标，会在菜单显示", Default: ""},
		{Name: "badge_type", Type: field.TypeString, Comment: "用于配置页面的徽标类型，dot 为小红点，normal 为文本", Default: "normal"},
		{Name: "badge_variants", Type: field.TypeString, Comment: "用于配置页面的徽标颜色。类型：'default' | 'destructive' | 'primary' | 'success' | 'warning' | string", Default: "success"},
	}
	// SysMenuTable holds the schema information for the "sys_menu" table.
	SysMenuTable = &schema.Table{
		Name:       "sys_menu",
		Comment:    "菜单表",
		Columns:    SysMenuColumns,
		PrimaryKey: []*schema.Column{SysMenuColumns[0]},
	}
	// SysProjectionSourceStatusColumns holds the columns for the "sys_projection_source_status" table.
	SysProjectionSourceStatusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "数据唯一标识"},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "source_service", Type: field.TypeString, Unique: true, Comment: "投影源服务编码"},
		{Name: "domain_code", Type: field.TypeString, Comment: "所属业务域", Default: ""},
		{Name: "sync_mode", Type: field.TypeString, Comment: "同步模式", Default: ""},
		{Name: "state", Type: field.TypeString, Comment: "当前状态", Default: ""},
		{Name: "last_snapshot_revision", Type: field.TypeUint64, Comment: "最后一次快照版本", Default: 0},
		{Name: "last_sync_time", Type: field.TypeString, Comment: "最后同步时间", Default: ""},
		{Name: "last_error", Type: field.TypeString, Comment: "最后错误信息", Default: ""},
		{Name: "description", Type: field.TypeString, Comment: "描述", Default: ""},
	}
	// SysProjectionSourceStatusTable holds the schema information for the "sys_projection_source_status" table.
	SysProjectionSourceStatusTable = &schema.Table{
		Name:       "sys_projection_source_status",
		Comment:    "权限投影源状态表",
		Columns:    SysProjectionSourceStatusColumns,
		PrimaryKey: []*schema.Column{SysProjectionSourceStatusColumns[0]},
	}
	// SysResourcesColumns holds the columns for the "sys_resources" table.
	SysResourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "数据唯一标识"},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Comment: "资源名称"},
		{Name: "type", Type: field.TypeString, Comment: "资源类型"},
		{Name: "value", Type: field.TypeString, Comment: "资源值"},
		{Name: "method", Type: field.TypeString, Comment: "对资源的操作"},
		{Name: "description", Type: field.TypeString, Comment: "资源的描述"},
	}
	// SysResourcesTable holds the schema information for the "sys_resources" table.
	SysResourcesTable = &schema.Table{
		Name:       "sys_resources",
		Comment:    "系统资源表",
		Columns:    SysResourcesColumns,
		PrimaryKey: []*schema.Column{SysResourcesColumns[0]},
	}
	// SysRoleColumns holds the columns for the "sys_role" table.
	SysRoleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Comment: "角色名称"},
		{Name: "value", Type: field.TypeString, Comment: "角色值"},
		{Name: "status", Type: field.TypeBool, Comment: "0-禁用，1-启用"},
		{Name: "desc", Type: field.TypeString, Comment: "简介"},
		{Name: "menus", Type: field.TypeJSON, Comment: "权限菜单ID列表"},
	}
	// SysRoleTable holds the schema information for the "sys_role" table.
	SysRoleTable = &schema.Table{
		Name:       "sys_role",
		Comment:    "角色表",
		Columns:    SysRoleColumns,
		PrimaryKey: []*schema.Column{SysRoleColumns[0]},
	}
	// SysServiceRegistryColumns holds the columns for the "sys_service_registry" table.
	SysServiceRegistryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "数据唯一标识"},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "service_code", Type: field.TypeString, Unique: true, Comment: "服务编码"},
		{Name: "service_name", Type: field.TypeString, Comment: "服务名称"},
		{Name: "domain_code", Type: field.TypeString, Comment: "所属业务域"},
		{Name: "http_prefix", Type: field.TypeString, Comment: "HTTP 前缀", Default: ""},
		{Name: "grpc_service", Type: field.TypeString, Comment: "gRPC 服务名", Default: ""},
		{Name: "status", Type: field.TypeBool, Comment: "0-禁用，1-启用", Default: true},
		{Name: "projection_enabled", Type: field.TypeBool, Comment: "是否启用权限投影", Default: false},
		{Name: "description", Type: field.TypeString, Comment: "描述", Default: ""},
	}
	// SysServiceRegistryTable holds the schema information for the "sys_service_registry" table.
	SysServiceRegistryTable = &schema.Table{
		Name:       "sys_service_registry",
		Comment:    "平台服务注册表",
		Columns:    SysServiceRegistryColumns,
		PrimaryKey: []*schema.Column{SysServiceRegistryColumns[0]},
	}
	// SysSiteMessageColumns holds the columns for the "sys_site_message" table.
	SysSiteMessageColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "数据唯一标识"},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "title", Type: field.TypeString, Comment: "消息标题"},
		{Name: "content", Type: field.TypeString, Comment: "消息正文"},
		{Name: "category", Type: field.TypeString, Comment: "消息分类", Default: "system"},
		{Name: "status", Type: field.TypeString, Comment: "消息状态 draft|scheduled|published|recalled", Default: "published"},
		{Name: "receiver_count", Type: field.TypeInt64, Comment: "接收人数", Default: 0},
		{Name: "link", Type: field.TypeString, Comment: "消息跳转链接", Default: ""},
		{Name: "sender_id", Type: field.TypeString, Comment: "发布人ID", Default: ""},
		{Name: "sender_name", Type: field.TypeString, Comment: "发布人名称", Default: ""},
		{Name: "scheduled_publish_time", Type: field.TypeTime, Nullable: true, Comment: "定时发布时间"},
		{Name: "published_time", Type: field.TypeTime, Nullable: true, Comment: "实际发布时间"},
		{Name: "recalled_time", Type: field.TypeTime, Nullable: true, Comment: "撤回时间"},
	}
	// SysSiteMessageTable holds the schema information for the "sys_site_message" table.
	SysSiteMessageTable = &schema.Table{
		Name:       "sys_site_message",
		Comment:    "站内信发布记录表",
		Columns:    SysSiteMessageColumns,
		PrimaryKey: []*schema.Column{SysSiteMessageColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sitemessage_create_time",
				Unique:  false,
				Columns: []*schema.Column{SysSiteMessageColumns[1]},
			},
			{
				Name:    "sitemessage_category",
				Unique:  false,
				Columns: []*schema.Column{SysSiteMessageColumns[5]},
			},
			{
				Name:    "sitemessage_status",
				Unique:  false,
				Columns: []*schema.Column{SysSiteMessageColumns[6]},
			},
			{
				Name:    "sitemessage_scheduled_publish_time",
				Unique:  false,
				Columns: []*schema.Column{SysSiteMessageColumns[11]},
			},
		},
	}
	// SysSiteMessageReceiptColumns holds the columns for the "sys_site_message_receipt" table.
	SysSiteMessageReceiptColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "数据唯一标识"},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "message_id", Type: field.TypeString, Comment: "站内信ID"},
		{Name: "user_id", Type: field.TypeString, Comment: "收件用户ID"},
		{Name: "is_read", Type: field.TypeBool, Comment: "是否已读", Default: false},
		{Name: "read_time", Type: field.TypeTime, Comment: "已读时间"},
	}
	// SysSiteMessageReceiptTable holds the schema information for the "sys_site_message_receipt" table.
	SysSiteMessageReceiptTable = &schema.Table{
		Name:       "sys_site_message_receipt",
		Comment:    "站内信收件记录表",
		Columns:    SysSiteMessageReceiptColumns,
		PrimaryKey: []*schema.Column{SysSiteMessageReceiptColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sitemessagereceipt_user_id_is_read",
				Unique:  false,
				Columns: []*schema.Column{SysSiteMessageReceiptColumns[4], SysSiteMessageReceiptColumns[5]},
			},
			{
				Name:    "sitemessagereceipt_message_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{SysSiteMessageReceiptColumns[3], SysSiteMessageReceiptColumns[4]},
			},
			{
				Name:    "sitemessagereceipt_create_time",
				Unique:  false,
				Columns: []*schema.Column{SysSiteMessageReceiptColumns[1]},
			},
		},
	}
	// SysLogColumns holds the columns for the "sys_log" table.
	SysLogColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "数据唯一标识"},
		{Name: "user_id", Type: field.TypeString, Comment: "用户id"},
		{Name: "user_name", Type: field.TypeString, Comment: "用户名"},
		{Name: "is_login", Type: field.TypeBool, Comment: "是否登录日志"},
		{Name: "session_id", Type: field.TypeString, Comment: "会话ID"},
		{Name: "method", Type: field.TypeString, Comment: "请求方式GET|POST|PUT|DELETE|OPTIONS..."},
		{Name: "path", Type: field.TypeString, Comment: "请求地址"},
		{Name: "request_time", Type: field.TypeTime, Comment: "请求时间"},
		{Name: "ip_address", Type: field.TypeString, Comment: "IP地址"},
		{Name: "ip_location", Type: field.TypeString, Comment: "IP归属地"},
		{Name: "latency", Type: field.TypeInt64, Comment: "响应耗时ms"},
		{Name: "os", Type: field.TypeString, Comment: "平台"},
		{Name: "browser", Type: field.TypeString, Comment: "浏览器"},
		{Name: "user_agent", Type: field.TypeString, Comment: "访问代理"},
		{Name: "header", Type: field.TypeString, Comment: "请求头"},
		{Name: "get_params", Type: field.TypeString, Comment: "Get参数"},
		{Name: "post_data", Type: field.TypeString, Comment: "Post数据"},
		{Name: "res_code", Type: field.TypeInt32, Comment: "响应状态码"},
		{Name: "reason", Type: field.TypeString, Comment: "错误原因"},
		{Name: "res_status", Type: field.TypeBool, Comment: "请求状态"},
		{Name: "stack", Type: field.TypeString, Comment: "错误堆栈"},
		{Name: "create_time", Type: field.TypeTime},
	}
	// SysLogTable holds the schema information for the "sys_log" table.
	SysLogTable = &schema.Table{
		Name:       "sys_log",
		Comment:    "系统日志表",
		Columns:    SysLogColumns,
		PrimaryKey: []*schema.Column{SysLogColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "syslogrecord_session_id",
				Unique:  false,
				Columns: []*schema.Column{SysLogColumns[4]},
			},
			{
				Name:    "syslogrecord_user_id",
				Unique:  false,
				Columns: []*schema.Column{SysLogColumns[1]},
			},
			{
				Name:    "syslogrecord_path",
				Unique:  false,
				Columns: []*schema.Column{SysLogColumns[6]},
			},
			{
				Name:    "syslogrecord_request_time",
				Unique:  false,
				Columns: []*schema.Column{SysLogColumns[7]},
			},
			{
				Name:    "syslogrecord_ip_address",
				Unique:  false,
				Columns: []*schema.Column{SysLogColumns[8]},
			},
			{
				Name:    "syslogrecord_latency",
				Unique:  false,
				Columns: []*schema.Column{SysLogColumns[10]},
			},
			{
				Name:    "syslogrecord_is_login",
				Unique:  false,
				Columns: []*schema.Column{SysLogColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					Where: "is_login = true",
				},
			},
			{
				Name:    "syslogrecord_is_login_user_name",
				Unique:  false,
				Columns: []*schema.Column{SysLogColumns[3], SysLogColumns[2]},
				Annotation: &entsql.IndexAnnotation{
					Where: "is_login = true",
				},
			},
			{
				Name:    "syslogrecord_res_code",
				Unique:  false,
				Columns: []*schema.Column{SysLogColumns[17]},
				Annotation: &entsql.IndexAnnotation{
					Where: "res_code != 200",
				},
			},
			{
				Name:    "syslogrecord_res_status",
				Unique:  false,
				Columns: []*schema.Column{SysLogColumns[19]},
				Annotation: &entsql.IndexAnnotation{
					Where: "res_status = false",
				},
			},
		},
	}
	// SysUserColumns holds the columns for the "sys_user" table.
	SysUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "username", Type: field.TypeString, Comment: "用户名"},
		{Name: "password", Type: field.TypeString, Comment: "密码"},
		{Name: "nickname", Type: field.TypeString, Nullable: true, Comment: "昵称"},
		{Name: "email", Type: field.TypeString, Nullable: true, Comment: "邮箱"},
		{Name: "status", Type: field.TypeInt8, Comment: "0-锁定，1-正常"},
		{Name: "avatar", Type: field.TypeString, Comment: "头像"},
		{Name: "desc", Type: field.TypeString, Comment: "备注"},
		{Name: "extension", Type: field.TypeString, Comment: "扩展信息"},
	}
	// SysUserTable holds the schema information for the "sys_user" table.
	SysUserTable = &schema.Table{
		Name:       "sys_user",
		Comment:    "用户信息表",
		Columns:    SysUserColumns,
		PrimaryKey: []*schema.Column{SysUserColumns[0]},
	}
	// SysUserRoleBindingColumns holds the columns for the "sys_user_role_binding" table.
	SysUserRoleBindingColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString, Comment: "用户ID"},
		{Name: "role_id", Type: field.TypeInt64, Comment: "角色ID"},
	}
	// SysUserRoleBindingTable holds the schema information for the "sys_user_role_binding" table.
	SysUserRoleBindingTable = &schema.Table{
		Name:       "sys_user_role_binding",
		Comment:    "业务用户角色绑定表",
		Columns:    SysUserRoleBindingColumns,
		PrimaryKey: []*schema.Column{SysUserRoleBindingColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "userrolebinding_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{SysUserRoleBindingColumns[3], SysUserRoleBindingColumns[4]},
			},
		},
	}
	// APIResourcesRolesColumns holds the columns for the "api_resources_roles" table.
	APIResourcesRolesColumns = []*schema.Column{
		{Name: "api_resources_id", Type: field.TypeString},
		{Name: "role_id", Type: field.TypeInt64},
	}
	// APIResourcesRolesTable holds the schema information for the "api_resources_roles" table.
	APIResourcesRolesTable = &schema.Table{
		Name:       "api_resources_roles",
		Columns:    APIResourcesRolesColumns,
		PrimaryKey: []*schema.Column{APIResourcesRolesColumns[0], APIResourcesRolesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_resources_roles_api_resources_id",
				Columns:    []*schema.Column{APIResourcesRolesColumns[0]},
				RefColumns: []*schema.Column{SysAPIResourcesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "api_resources_roles_role_id",
				Columns:    []*schema.Column{APIResourcesRolesColumns[1]},
				RefColumns: []*schema.Column{SysRoleColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ResourceRolesColumns holds the columns for the "resource_roles" table.
	ResourceRolesColumns = []*schema.Column{
		{Name: "resource_id", Type: field.TypeString},
		{Name: "role_id", Type: field.TypeInt64},
	}
	// ResourceRolesTable holds the schema information for the "resource_roles" table.
	ResourceRolesTable = &schema.Table{
		Name:       "resource_roles",
		Columns:    ResourceRolesColumns,
		PrimaryKey: []*schema.Column{ResourceRolesColumns[0], ResourceRolesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "resource_roles_resource_id",
				Columns:    []*schema.Column{ResourceRolesColumns[0]},
				RefColumns: []*schema.Column{SysResourcesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "resource_roles_role_id",
				Columns:    []*schema.Column{ResourceRolesColumns[1]},
				RefColumns: []*schema.Column{SysRoleColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysAPIResourcesTable,
		SysBusinessDomainTable,
		SysDeptTable,
		SysMenuTable,
		SysProjectionSourceStatusTable,
		SysResourcesTable,
		SysRoleTable,
		SysServiceRegistryTable,
		SysSiteMessageTable,
		SysSiteMessageReceiptTable,
		SysLogTable,
		SysUserTable,
		SysUserRoleBindingTable,
		APIResourcesRolesTable,
		ResourceRolesTable,
	}
)

func init() {
	SysAPIResourcesTable.Annotation = &entsql.Annotation{
		Table: "sys_api_resources",
	}
	SysBusinessDomainTable.Annotation = &entsql.Annotation{
		Table: "sys_business_domain",
	}
	SysDeptTable.ForeignKeys[0].RefTable = SysDeptTable
	SysDeptTable.Annotation = &entsql.Annotation{
		Table: "sys_dept",
	}
	SysMenuTable.Annotation = &entsql.Annotation{
		Table: "sys_menu",
	}
	SysProjectionSourceStatusTable.Annotation = &entsql.Annotation{
		Table: "sys_projection_source_status",
	}
	SysResourcesTable.Annotation = &entsql.Annotation{
		Table: "sys_resources",
	}
	SysRoleTable.Annotation = &entsql.Annotation{
		Table: "sys_role",
	}
	SysServiceRegistryTable.Annotation = &entsql.Annotation{
		Table: "sys_service_registry",
	}
	SysSiteMessageTable.Annotation = &entsql.Annotation{
		Table: "sys_site_message",
	}
	SysSiteMessageReceiptTable.Annotation = &entsql.Annotation{
		Table: "sys_site_message_receipt",
	}
	SysLogTable.Annotation = &entsql.Annotation{
		Table: "sys_log",
	}
	SysUserTable.Annotation = &entsql.Annotation{
		Table: "sys_user",
	}
	SysUserRoleBindingTable.Annotation = &entsql.Annotation{
		Table: "sys_user_role_binding",
	}
	APIResourcesRolesTable.ForeignKeys[0].RefTable = SysAPIResourcesTable
	APIResourcesRolesTable.ForeignKeys[1].RefTable = SysRoleTable
	ResourceRolesTable.ForeignKeys[0].RefTable = SysResourcesTable
	ResourceRolesTable.ForeignKeys[1].RefTable = SysRoleTable
}
