server:
  http:
    addr: 0.0.0.0:8030
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9030
    timeout: 1s
data:
  database:
    driver: pgx
    source: postgresql://postgres:postgres.666@127.0.0.1:25432/admin?sslmode=disable
  redis:
    addr: 127.0.0.1:26379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  api_key: auth-service-secret
  whitelist:
    - /api.admin.service.v1.AdminService/CreateSysLog
    - /api.admin.service.v1.AdminService/GetAuthRoleCatalog
    - /api.admin.service.v1.AdminService/GetAuthApiCatalog
    - /api.admin.service.v1.AdminService/GetAuthRole
    - /api.admin.service.v1.AdminService/GetApiList
    - /api.admin.service.v1.AdminService/ResolveRoleValues
    - /api.admin.service.v1.AdminService/GetUserRoleBinding
    - /api.admin.service.v1.AdminService/ListUserRoleBindings
    - /api.admin.service.v1.AdminService/GetServiceRegistryList
services:
  user:
    grpc_endpoint: 127.0.0.1:9010
  auth:
    grpc_endpoint: 127.0.0.1:9020
  common:
    grpc_endpoint: 127.0.0.1:9040
logger:
  level: info
  filename: logs/admin-service.log
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: false
