name: Docker Image CI

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        images="base-server:${{ github.ref }}"
        docker build . --file Dockerfile --tag "${image}"
        docker save "${image}" -o "${image}-amd64.tar"

    - name: Compress the TAR files
      run: tar -czf "${image}-amd64.tar.gz" *-amd64.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: ${image}-amd64.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-amd64.tar
