name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  pull_and_package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, user, admin, common]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean up Docker to free space
        run: |
          docker system prune -a -f
          docker volume prune -f

      - name: Build the Docker image
        run: |
          image="base-server-${{ matrix.service }}:${{ github.ref_name }}"
          docker build . --file Dockerfile --build-arg SERVICE=${{ matrix.service }} --tag "${image}"
          docker save "${image}" -o "${{ matrix.service }}-amd64.tar"

      - name: Compress TAR file
        run: tar -czf "${{ matrix.service }}-images.tar.gz" "${{ matrix.service }}-amd64.tar"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ matrix.service }}
          path: ${{ matrix.service }}-images.tar.gz
          retention-days: 1
